//
//  Question.swift
//  Goods Store
//
//  Created by Алексей Пасынков on 30.11.2020.
//

struct Question {
    let text: String
    let type: ResponseType
    let answers: [Answers]
    
    static let allQuestion: [Question] = [
        Question(text: "Выберете ценновой придел", type: .range,
                 answers: [
                    Answers(text: "< 1000", type: [.model1_1,
                                                   .model1_2,
                                                   .model1_3,
                                                    ]),
                    
                    Answers(text: "< 3000", type: [.model2_1,
                                                   .model2_2,
                                                   .model2_3,
                                                   .model2_4,
                                                   .model2_5,
                                                   .model2_6,
                                                   .model2_7,
                                                   .model2_8,
                                                   .model2_9,
                                                  ]),
                   
                    
                    Answers(text: "< 5000", type: [.model3_1,
                                                   .model3_2,
                                                   .model3_3,
                                                   .model3_4,
                                                   .model3_5,
                                                   .model3_6,
                                                   .model3_7,
                                                   .model3_8,
                                                   .model3_9,
                                                   .model3_10,
                                                   .model3_11,
                                                   .model3_12,
                                                    ]),
                    
                    
                    Answers(text: "< 7000", type: [.model4_1,
                                                   .model4_2,
                                                   .model4_3,
                                                   .model4_4,
                                                   .model4_5,
                                                   .model4_6,
                                                   .model4_7,
                                                   .model4_8,
                                                   .model4_9,
                                                   .model4_10,
                                                   .model4_11,
                                                   .model4_12,
                                                    ]),
                
                    Answers(text: "> 7000", type: [.model5_1,
                                                   .model5_2,
                                                   .model5_3,
                                                   .model5_4,
                                                   .model5_5,
                                                   .model5_6,
                                                   .model5_7,
                                                   .model5_8,
                                                   .model5_9,
                                                   .model5_10,
                                                   .model5_11,
                                                   .model5_12,
                                                   .model5_13,
                                                   .model5_14,
                                                   ]),
                   
                 ]),
        Question(text: "Выберете производителей", type: .multiple,
                 answers: [
                    Answers(text: "Другие", type: [.model1_1,
                                                   .model1_2,
                                                   .model3_12,
                                                   .model4_10,
                                                   .model4_11,
                                                   .model5_5,
                                                  ]),
                    
                    Answers(text: "Redmond", type: [.model2_6,
                                                    .model2_7,
                                                    .model3_6,
                                                    .model3_7,
                                                    ]),
                   
                    Answers(text: "Polaris", type: [.model2_5,
                                                    .model2_9,
                                                    .model3_4,
                                                    .model3_5,
                                                    ]),
                    
                    Answers(text: "Bosch", type: [.model2_3,
                                                  .model3_1,
                                                  .model4_2,
                                                  .model5_11,
                                                 ]),
                    
                    
                    Answers(text: "Philips", type: [.model1_3,
                                                    .model2_1,
                                                    .model3_9,
                                                    .model3_11,
                                                    .model4_1,
                                                    .model4_3,
                                                    .model4_5,
                                                    .model4_6,
                                                    .model4_8,
                                                    .model4_9,
                                                    .model5_2,
                                                    .model5_3,
                                                    .model5_7,
                                                    .model5_8,
                                                    .model5_9,
                                                    .model5_12,
                                                    .model5_13,
                                                    ]),
                
                    Answers(text: "Braun", type: [.model2_4,
                                                  .model3_2,
                                                  .model3_3,
                                                  .model4_4,
                                                  .model4_12,
                                                  .model5_1,
                                                   ]),
                    Answers(text: "Tefal", type: [.model2_2,
                                                  .model3_8,
                                                  .model3_10,
                                                  .model4_7,
                                                  .model5_4,
                                                  .model5_6,
                                                  .model5_10,
                                                  .model5_14,
                                                   ]),
                 ]),
        Question(text: "Какие доп. функции вы бы хотели получить?", type: .multiple,
                 answers: [
                    Answers(text: "Противокапельная система", type: [.model1_1,
                                                                     .model1_2,
                                                                     .model2_1,
                                                                     .model2_2,
                                                                     .model2_3,
                                                                     .model2_5,
                                                                     .model2_6,
                                                                     .model2_7,
                                                                     .model2_8,
                                                                     .model2_9,
                                                                     .model3_1,
                                                                     .model3_2,
                                                                     .model3_3,
                                                                     .model3_4,
                                                                     .model3_5,
                                                                     .model3_6,
                                                                     .model3_7,
                                                                     .model3_8,
                                                                     .model3_9,
                                                                     .model3_10,
                                                                     .model3_11,
                                                                     .model3_12,
                                                                     .model4_1,
                                                                     .model4_2,
                                                                     .model4_3,
                                                                     .model4_4,
                                                                     .model4_5,
                                                                     .model4_6,
                                                                     .model4_7,
                                                                     .model4_8,
                                                                     .model4_9,
                                                                     .model4_10,
                                                                     .model4_11,
                                                                     .model4_12,
                                                                     .model5_1,
                                                                     .model5_2,
                                                                     .model5_3,
                                                                     .model5_4,
                                                                     .model5_5,
                                                                     .model5_6,
                                                                     .model5_7,
                                                                     .model5_8,
                                                                     .model5_9,
                                                                     .model5_10,
                                                                     .model5_11,
                                                                     .model5_12,
                                                                     .model5_13,
                                                                     .model5_14,
                                                    
                                                    ]),
                    
                    Answers(text: "Функ.самоотчиски", type: [.model1_3,
                                                             .model2_1,
                                                             .model2_2,
                                                             .model2_3,
                                                             .model2_4,
                                                             .model2_5,
                                                             .model2_6,
                                                             .model2_7,
                                                             .model2_8,
                                                             .model2_9,
                                                             .model3_1,
                                                             .model3_3,
                                                             .model3_4,
                                                             .model3_5,
                                                             .model3_6,
                                                             .model3_7,
                                                             .model3_8,
                                                             .model3_9,
                                                             .model3_10,
                                                             .model3_11,
                                                             .model3_12,
                                                             .model4_1,
                                                             .model4_2,
                                                             .model4_3,
                                                             .model4_4,
                                                             .model4_5,
                                                             .model4_6,
                                                             .model4_7,
                                                             .model4_8,
                                                             .model4_9,
                                                             .model4_10,
                                                             .model4_11,
                                                             .model4_12,
                                                             .model5_1,
                                                             .model5_2,
                                                             .model5_3,
                                                             .model5_4,
                                                             .model5_5,
                                                             .model5_6,
                                                             .model5_7,
                                                             .model5_8,
                                                             .model5_9,
                                                             .model5_10,
                                                             .model5_11,
                                                             .model5_12,
                                                             .model5_13,
                                                             .model5_14,
                                                    
                                                    ]),
                   
                    
                    Answers(text: "Авто.выбор темп.", type: [.model3_10,
                                                             .model5_8,
                                                             .model5_9,
                                                             .model5_10,
                                                             .model5_11,
                                                    ]),
                    
                    
                    Answers(text: "вертикальное отпаривоние", type: [.model1_1,
                                                                     .model1_2,
                                                                     .model1_3,
                                                                     .model2_1,
                                                                     .model2_2,
                                                                     .model2_3,
                                                                     .model2_4,
                                                                     .model2_5,
                                                                     .model2_6,
                                                                     .model2_7,
                                                                     .model2_8,
                                                                     .model2_9,
                                                                     .model3_1,
                                                                     .model3_2,
                                                                     .model3_3,
                                                                     .model3_4,
                                                                     .model3_5,
                                                                     .model3_6,
                                                                     .model3_7,
                                                                     .model3_8,
                                                                     .model3_9,
                                                                     .model3_10,
                                                                     .model3_11,
                                                                     .model3_12,
                                                                     .model4_1,
                                                                     .model4_2,
                                                                     .model4_3,
                                                                     .model4_4,
                                                                     .model4_5,
                                                                     .model4_6,
                                                                     .model4_7,
                                                                     .model4_8,
                                                                     .model4_9,
                                                                     .model4_10,
                                                                     .model4_11,
                                                                     .model4_12,
                                                                     .model5_1,
                                                                     .model5_2,
                                                                     .model5_3,
                                                                     .model5_4,
                                                                     .model5_5,
                                                                     .model5_6,
                                                                     .model5_7,
                                                                     .model5_8,
                                                                     .model5_9,
                                                                     .model5_10,
                                                                     .model5_11,
                                                                     .model5_12,
                                                                     .model5_13,
                                                                     .model5_14,
                                                    ]),
                
                    Answers(text: "Синхрон. с телефон", type: [.model2_6,
                                                               .model3_7,
                                                               .model5_10,
                                                              ]),
                    
                    Answers(text: "Беспроводное использование", type: [.model3_5,
                                                                       .model2_9,
                                                                       .model4_8,
                                                                       .model5_10,
                                                                      ]),
                    
                    Answers(text: "Защита от накипи", type: [.model1_3,
                                                             .model2_1,
                                                             .model2_2,
                                                             .model2_3,
                                                             .model2_4,
                                                             .model2_5,
                                                             .model2_6,
                                                             .model2_7,
                                                             .model2_8,
                                                             .model2_9,
                                                             .model3_1,
                                                             .model3_2,
                                                             .model3_3,
                                                             .model3_4,
                                                             .model3_5,
                                                             .model3_6,
                                                             .model3_7,
                                                             .model3_8,
                                                             .model3_9,
                                                             .model3_10,
                                                             .model3_11,
                                                             .model3_12,
                                                             .model4_1,
                                                             .model4_2,
                                                             .model4_3,
                                                             .model4_4,
                                                             .model4_5,
                                                             .model4_6,
                                                             .model4_7,
                                                             .model4_8,
                                                             .model4_9,
                                                             .model4_10,
                                                             .model4_11,
                                                             .model4_12,
                                                             .model5_1,
                                                             .model5_2,
                                                             .model5_3,
                                                             .model5_4,
                                                             .model5_5,
                                                             .model5_6,
                                                             .model5_7,
                                                             .model5_8,
                                                             .model5_9,
                                                             .model5_10,
                                                             .model5_11,
                                                             .model5_12,
                                                             .model5_13,
                                                             .model5_14,
                                                   ]),
                    
                    Answers(text: "Паровой удар", type: [.model1_1,
                                                         .model1_2,
                                                         .model1_3,
                                                         .model2_1,
                                                         .model2_2,
                                                         .model2_3,
                                                         .model2_4,
                                                         .model2_5,
                                                         .model2_6,
                                                         .model2_7,
                                                         .model2_8,
                                                         .model2_9,
                                                         .model3_1,
                                                         .model3_2,
                                                         .model3_3,
                                                         .model3_4,
                                                         .model3_5,
                                                         .model3_6,
                                                         .model3_7,
                                                         .model3_8,
                                                         .model3_9,
                                                         .model3_10,
                                                         .model3_11,
                                                         .model3_12,
                                                         .model4_1,
                                                         .model4_2,
                                                         .model4_3,
                                                         .model4_4,
                                                         .model4_5,
                                                         .model4_6,
                                                         .model4_7,
                                                         .model4_8,
                                                         .model4_9,
                                                         .model4_10,
                                                         .model4_11,
                                                         .model4_12,
                                                         .model5_1,
                                                         .model5_2,
                                                         .model5_3,
                                                         .model5_4,
                                                         .model5_5,
                                                         .model5_6,
                                                         .model5_7,
                                                         .model5_8,
                                                         .model5_9,
                                                         .model5_10,
                                                         .model5_11,
                                                         .model5_12,
                                                         .model5_13,
                                                         .model5_14,
                                                   ]),
                    
                    Answers(text: "Авто.отключение", type: [.model1_1,
                                                            .model1_2,
                                                            .model2_1,
                                                            .model2_2,
                                                            .model2_3,
                                                            .model2_4,
                                                            .model2_5,
                                                            .model2_6,
                                                            .model2_8,
                                                            .model3_1,
                                                            .model3_2,
                                                            .model3_6,
                                                            .model3_7,
                                                            .model3_8,
                                                            .model3_9,
                                                            .model3_10,
                                                            .model3_11,
                                                            .model3_12,
                                                            .model4_1,
                                                            .model4_2,
                                                            .model4_3,
                                                            .model4_4,
                                                            .model4_5,
                                                            .model4_6,
                                                            .model4_7,
                                                            .model4_8,
                                                            .model4_9,
                                                            .model4_10,
                                                            .model4_11,
                                                            .model4_12,
                                                            .model5_1,
                                                            .model5_2,
                                                            .model5_3,
                                                            .model5_4,
                                                            .model5_5,
                                                            .model5_6,
                                                            .model5_7,
                                                            .model5_8,
                                                            .model5_9,
                                                            .model5_10,
                                                            .model5_11,
                                                            .model5_12,
                                                            .model5_13,
                                                            .model5_14,
                                                   ]),
                   
                 ]),
        Question(text: "Выберете рейтинг утюга", type: .single,
                 answers: [
                    Answers(text: "< 4.5", type: [.model1_1,
                                                  .model1_2,
                                                  .model2_1,
                                                  .model2_2,
                                                  .model2_3,
                                                  .model2_4,
                                                  .model3_2,
                                                  .model3_3,
                                                  .model3_8,
                                                  .model4_2,
                                                  .model4_6,
                                                  .model4_11,
                                                  .model5_2,
                                                  .model5_9,
                                                  ]),
                    
                    Answers(text: "> 4.5", type: [.model1_3,
                                                  .model2_5,
                                                  .model2_6,
                                                  .model2_7,
                                                  .model2_8,
                                                  .model2_9,
                                                  .model3_1,
                                                  .model3_4,
                                                  .model3_5,
                                                  .model3_6,
                                                  .model3_7,
                                                  .model3_9,
                                                  .model3_10,
                                                  .model3_11,
                                                  .model3_12,
                                                  .model4_1,
                                                  .model4_3,
                                                  .model4_4,
                                                  .model4_5,
                                                  .model4_7,
                                                  .model4_8,
                                                  .model4_9,
                                                  .model4_10,
                                                  .model4_12,
                                                  .model5_1,
                                                  .model5_3,
                                                  .model5_4,
                                                  .model5_5,
                                                  .model5_6,
                                                  .model5_7,
                                                  .model5_8,
                                                  .model5_10,
                                                  .model5_11,
                                                  .model5_12,
                                                  .model5_13,
                                                  .model5_14,
                                                    ]),
                   
                    
                 ]),
        Question(text: "Выберете мощность утюга", type: .single,
                 answers: [
                    Answers(text: "< 2500 Вт", type: [.model1_1,
                                                      .model1_2,
                                                      .model1_3,
                                                      .model2_1,
                                                      .model2_2,
                                                      .model2_3,
                                                      .model2_4,
                                                      .model2_7,
                                                      .model2_9,
                                                      .model3_2,
                                                      .model3_3,
                                                      .model3_4,
                                                      .model3_6,
                                                      .model3_9,
                                                      .model3_10,
                                                      .model3_11,
                                                      .model4_1,
                                                      .model4_3,
                                                      .model4_4,
                                                      .model4_8,
                                                      .model4_10,
                                                      .model4_11,
                                                      .model4_12,
                                                      .model5_1,
                                                      .model5_5,
                                                      .model5_6,
                                                      .model5_9,
                                                  ]),
                    
                    Answers(text: "> 2500 Вт", type: [.model2_5,
                                                      .model2_6,
                                                      .model2_7,
                                                      .model2_8,
                                                      .model3_1,
                                                      .model3_5,
                                                      .model3_7,
                                                      .model3_12,
                                                      .model4_2,
                                                      .model4_5,
                                                      .model4_6,
                                                      .model4_7,
                                                      .model4_9,
                                                      .model5_2,
                                                      .model5_3,
                                                      .model5_4,
                                                      .model5_7,
                                                      .model5_8,
                                                      .model5_10,
                                                      .model5_11,
                                                      .model5_12,
                                                      .model5_13,
                                                      .model5_14,
                                                    ]),
                 ]),
        ]
}
